#!/usr/bin/env python3
"""
03_generate_restraints.py
=========================
Generate HADDOCK3 restraint files for ERY2-4 / CTLA-4 docking.

Restraint types generated:
  1. AIR (Ambiguous Interaction Restraints) - main docking restraints
  2. Unambiguous restraints - disulfide bond in ERY2-4
  3. Hydrogen bond restraints (optional)

Scientific basis:
  - CTLA-4 active residues: B7-1/CTLA-4 interface from PDB 1I8L
  - ERY2-4 active residues: Trp residues (esp. Trp33, L33W mutation)
  - ERY2-4 competes with B7-1 (paper Fig 3c) -> same epitope on CTLA-4
  - No CD28 binding -> CTLA-4-specific surface recognition

Reference: Ramanayake et al. ACS Chem. Biol. 2020, 15, 360-368
           Stamper et al. Nature 2001 (1I8L)
"""

import json
from pathlib import Path

# ─── Paths ────────────────────────────────────────────────────────────────────
INPUT_RESIDUES  = Path("data/input/residues.json")
OUTPUT_DIR      = Path("data/output/03_restraints")
RECEPTOR_PDB    = Path("data/output/01_receptor/ctla4_final.pdb")
LIGAND_PDB      = Path("data/output/02_peptide/ery2-4_final.pdb")

# ─── HADDOCK CNS restraint parameters ─────────────────────────────────────────
AIR_DIST_UPPER  = 3.0   # Angstroms - upper bound for AIR
AIR_DIST_LOWER  = 0.0   # Angstroms - lower bound
SS_DIST         = 2.03  # Angstroms - S-S bond distance
SS_UPPER        = 2.1
SS_LOWER        = 1.9


def load_residues() -> dict:
    with open(INPUT_RESIDUES) as f:
        return json.load(f)


def generate_air_restraints(residues: dict) -> str:
    """
    Generate CNS-format AIR restraints.
    Format: assign (selection1) (selection2) distance lower upper
    """
    ctla4 = residues["CTLA4"]
    ery24 = residues["ERY2-4"]

    lines = []
    lines.append("!" + "=" * 70)
    lines.append("! AIR Restraints: ERY2-4 / CTLA-4 Docking")
    lines.append("! Generated by 03_generate_restraints.py")
    lines.append("!")
    lines.append("! Scientific basis:")
    lines.append("!   - CTLA-4 residues: B7-1 binding interface (PDB 1I8L)")
    lines.append("!   - ERY2-4 residues: Trp-rich face (esp. Trp33 = L33W)")
    lines.append("!   - Competition assay confirms overlapping epitope")
    lines.append("!" + "=" * 70)
    lines.append("")

    # Active-Active restraints (strongest evidence)
    lines.append("! === ACTIVE-ACTIVE RESTRAINTS ===")
    lines.append("! Between key residues on both molecules")
    lines.append("")

    rec_chain  = ctla4["chain"]
    lig_chain  = ery24["chain"]
    rec_active = ctla4["active"]
    lig_active = ery24["active"]
    rec_passive = ctla4["passive"]
    lig_passive = ery24["passive"]

    # Combine active + passive for full ambiguous restraint set
    rec_all = rec_active + rec_passive
    lig_all = lig_active + lig_passive

    for r_res in rec_active:
        rec_sel = (
            f'(resid {r_res} and segid {rec_chain} and '
            f'(name CA or name CB or name N or name O))'
        )
        lig_atom_sels = []
        for l_res in lig_all:
            lig_atom_sels.append(
                f'(resid {l_res} and segid {lig_chain} and '
                f'(name CA or name CB or name N or name O))'
            )
        lig_combined = "\n        or ".join(lig_atom_sels)

        lines.append(f"! CTLA-4 residue {r_res} -> ERY2-4 interface")
        lines.append(
            f"assign {rec_sel}\n"
            f"       ({lig_combined})\n"
            f"       {AIR_DIST_UPPER:.1f} {AIR_DIST_LOWER:.1f} {AIR_DIST_UPPER:.1f}"
        )
        lines.append("")

    # Ligand active -> receptor
    lines.append("! === ERY2-4 ACTIVE -> CTLA-4 INTERFACE ===")
    for l_res in lig_active:
        lig_sel = (
            f'(resid {l_res} and segid {lig_chain} and '
            f'(name CA or name CB or name N or name O))'
        )
        rec_atom_sels = []
        for r_res in rec_all:
            rec_atom_sels.append(
                f'(resid {r_res} and segid {rec_chain} and '
                f'(name CA or name CB or name N or name O))'
            )
        rec_combined = "\n        or ".join(rec_atom_sels)

        lines.append(f"! ERY2-4 residue {l_res} -> CTLA-4 interface")
        lines.append(
            f"assign {lig_sel}\n"
            f"       ({rec_combined})\n"
            f"       {AIR_DIST_UPPER:.1f} {AIR_DIST_LOWER:.1f} {AIR_DIST_UPPER:.1f}"
        )
        lines.append("")

    return "\n".join(lines)


def generate_ssbond_restraints(residues: dict) -> str:
    """
    Generate unambiguous disulfide bond restraints for ERY2-4.
    Cys1 (SG) -- Cys40 (SG) = 2.03 Angstroms
    """
    ery24     = residues["ERY2-4"]
    chain     = ery24["chain"]
    ss_bonds  = ery24["disulfide"]

    lines = []
    lines.append("!" + "=" * 70)
    lines.append("! Unambiguous Restraints: ERY2-4 Disulfide Bond")
    lines.append("! Cys1 (SG) -- Cys40 (SG)")
    lines.append("! Cyclizes the HLH peptide for conformational stability")
    lines.append("!" + "=" * 70)
    lines.append("")

    for (res1, res2) in ss_bonds:
        sel1 = f"(resid {res1} and segid {chain} and name SG)"
        sel2 = f"(resid {res2} and segid {chain} and name SG)"
        lines.append(f"! Disulfide: Cys{res1} -- Cys{res2}")
        lines.append(
            f"assign {sel1}\n"
            f"       {sel2}\n"
            f"       {SS_DIST} {SS_LOWER} {SS_UPPER}"
        )
        lines.append("")

    return "\n".join(lines)


def generate_trp33_specific_restraints(residues: dict) -> str:
    """
    Generate specific restraints for Trp33 (L33W critical mutation)
    targeting the MYPPPY hydrophobic pocket of CTLA-4.
    
    These are based on:
    - L33W conserved across ALL affinity-matured variants (ERY2-1,4,6)
    - Trp inserts into hydrophobic groove around Met97/Tyr48 of CTLA-4
    """
    lines = []
    lines.append("!" + "=" * 70)
    lines.append("! Specific Restraints: Trp33 (L33W) -> CTLA-4 MYPPPY pocket")
    lines.append("! Trp33 is the primary hydrophobic anchor of ERY2-4")
    lines.append("! L33W mutation conserved across ERY2-1, ERY2-4, ERY2-6")
    lines.append("!" + "=" * 70)
    lines.append("")

    ery_chain  = residues["ERY2-4"]["chain"]
    ctla_chain = residues["CTLA4"]["chain"]

    # Trp33 CD2/CE2/CZ2 (aromatic ring) to CTLA-4 MYPPPY core (97-102)
    mypppy_residues = [97, 98, 99, 100, 101, 102]
    hydrophobic_residues = [48, 97]  # Tyr48, Met97 = hydrophobic pocket

    for ctla_res in hydrophobic_residues:
        sel_trp = (
            f"(resid 33 and segid {ery_chain} and "
            f"(name CD2 or name CE2 or name CZ2 or name CH2))"
        )
        sel_ctla = (
            f"(resid {ctla_res} and segid {ctla_chain} and "
            f"(name CA or name CB or name CG))"
        )
        lines.append(f"! Trp33(aromatic) -> CTLA-4 residue {ctla_res}")
        lines.append(
            f"assign {sel_trp}\n"
            f"       {sel_ctla}\n"
            f"       5.0 0.0 3.0"
        )
        lines.append("")

    return "\n".join(lines)


def write_restraint_file(content: str, path: Path, label: str):
    path.write_text(content)
    n_assigns = content.count("assign")
    print(f"[INFO] {label}: {path.name} ({n_assigns} assign statements)")


def generate_summary(residues: dict, out_dir: Path):
    """Write a human-readable summary of restraints."""
    ctla4 = residues["CTLA4"]
    ery24 = residues["ERY2-4"]

    summary = f"""
RESTRAINT SUMMARY
=================
ERY2-4 / CTLA-4 Docking (PDB: 1I8L)

CTLA-4 (Receptor, Chain {ctla4['chain']})
  Active  : {ctla4['active']}
  Passive : {ctla4['passive']}
  Key     : MYPPPY motif (97-102), Tyr48, Lys93

ERY2-4 (Ligand, Chain {ery24['chain']})
  Active  : {ery24['active']}
  Passive : {ery24['passive']}
  Disulfide: Cys{ery24['disulfide'][0][0]} -- Cys{ery24['disulfide'][0][1]}
  Key     : Trp33 = L33W (PRIMARY anchor)

Files Generated
  air_restraints.tbl       -> Main docking restraints
  ssbond_restraints.tbl    -> ERY2-4 disulfide bond
  trp33_restraints.tbl     -> Trp33 specific contacts

Scientific Basis
  - ERY2-4 competes with B7-1 for CTLA-4 binding (Fig 3c, paper)
  - No CD28 cross-reactivity (Fig 3e) -> CTLA-4-specific epitope
  - L33W conserved in ERY2-1/4/6 -> critical contact residue
  - KD = 196.8 nM (comparable to B7-1 affinity ~200 nM)
"""
    summary_path = out_dir / "restraints_summary.txt"
    summary_path.write_text(summary)
    print(f"[INFO] Summary: {summary_path}")


def main():
    print("=" * 60)
    print("  STEP 3: Generating HADDOCK3 Restraints")
    print("=" * 60)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    residues = load_residues()

    # Generate AIR restraints
    air_content = generate_air_restraints(residues)
    write_restraint_file(
        air_content,
        OUTPUT_DIR / "air_restraints.tbl",
        "AIR restraints"
    )

    # Generate SS-bond restraints
    ss_content = generate_ssbond_restraints(residues)
    write_restraint_file(
        ss_content,
        OUTPUT_DIR / "ssbond_restraints.tbl",
        "Disulfide restraints"
    )

    # Generate Trp33-specific restraints
    trp33_content = generate_trp33_specific_restraints(residues)
    write_restraint_file(
        trp33_content,
        OUTPUT_DIR / "trp33_restraints.tbl",
        "Trp33 specific restraints"
    )

    generate_summary(residues, OUTPUT_DIR)

    print(f"\n[DONE] All restraints saved to: {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
